### ISSUE TITLE
Use case when having multiple purpose commits

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/DevelopmentConventions#1]
I understand that the idea is to have a fine granularity that will imply that every commit is related to only one specific change. But would it be a good idea to have an explanation of how to handle the case when for some reason is very difficult or almost impossible to avoid committing only one change?
Maybe one solution would be to have a subject that tries to represent a general idea of the commit, and then the details could be somehow enumerated in the body?

**Comment by javier-godoy** [comment]
That's an interesting question. Those commits are, by definition and intention, not writeable under the convention (since it requires the subject to be "a succinct description of the change"). Hence, adopting the convention strongly suggest developers to organize their workflow so that they are able to avoid that kind of commits.

In that spirit, the textbook answer would be "go back and make multiple commits whenever possible", because "it discourages moving fast in a disorganized way". From the [Conventional Commits specification](https://github.com/conventional-commits/conventionalcommits.org/blob/master/content/v1.0.0/index.md#what-do-i-do-if-the-commit-conforms-to-more-than-one-of-the-commit-types) itself:
 
> ### What do I do if the commit conforms to more than one of the commit types?
> 
> _Go back and make multiple commits whenever possible_. Part of the benefit of Conventional Commits is its ability to drive us to make more organized commits and PRs.
> 
> ### Doesn’t this discourage rapid development and fast iteration?
> 
> _It discourages moving fast in a disorganized way_. It helps you be able to move fast long term across multiple projects with varied contributors.

Of course, theory and practice are -in theory- the same, but in practice they are not. How to handle those cases depends on which changes are entangled, and whether they can be subsumed into some (not-so-succinct) description that amounts to something more than "_if applied, this commit will apply changes_". After all, the commit will be reviewed, and the reviewer can request some rewriting, depending on the specific occurrence. 

Perhaps if you can illustrate the situation with some fictional example, we will be able to figure out what makes sense in those cases.

**Comment by mlopezFC** [comment]
I think that the key is in here:

> What do I do if the commit conforms to more than one of the commit types?
> Go back and make multiple commits whenever possible. Part of the benefit of Conventional Commits is its ability to drive us to make more organized commits and PRs.

"whenever possible" means it could be, that for some reason, sometimes it could not be possible to disassemble the commit and break it down to smaller ones. Is up to the reviewer (that is probably working in the same project and has a better idea) to decide if a strict implementation of conventional commits is required in that case or if maybe this particular point can be relaxed in order to solve other problems or goals with more priority.

I think that we could close this issue without making changes to our specification, what do you think?

**Comment by javier-godoy** [comment]
Closed with no changes.
