### ISSUE TITLE
Differences between ci and build types

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/DevelopmentConventions#10]
Sometimes is hard to choose the type of a commit, between these two options.
For example, a commit that has only these changes in the assembly.xml file:

`<excludes>
	<exclude>*-tests.jar</exclude>
</excludes>`

In this case, these changes were made at the same time (but maybe in different commits) as changes in the pom, for example adding the demo-jar profile. So, is it correct if the type of the assembly changes commit corelates to the type of the pom commit type?
Can we define in a more strict way the differences between these commit types? Having more examples about this could help too.

**Comment by javier-godoy** [comment]
Yes, we need to do that.

Our current definition is:
* `build:` Changes that affect the build system or external dependencies (e.g.: configure plugins and dependencies in pom.xml)
* `ci:` Changes to our CI configuration files and scripts, with no impact in the released artifact (e.g.: set metadata and profiles in pom.xml, edit DockerFile)

That is based on the [Angular commit convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) where these types were introduced:
* `build:` Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
* `ci:` Changes to our CI configuration files and scripts (example scopes: Circle, BrowserStack, SauceLabs)

An alternative wording is presented [here](https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/):
* `build:`  used to identify changes related to the build system (involving scripts, configurations or tools) and package dependencies.
* `ci:` used to identify changes related to the continuous integration and deployment system (involving scripts, configurations or tools).

Perphaps the situation with Maven isn't as clear as in the JavaScript ecosystem. There are some commits that are clearly `build` changes (such as updating a dependency, that is explicitly spelled out) and others are clearly `ci` (such as updating SCM information in pom.xml, since it's only used when preparing the release).

**Comment by javier-godoy** [comment]
One benefit of Conventional Commits is determining the version number from the commit messages alone (the "core" specification only defines `fix`, `feat`, and `BREAKING CHANGE`, which aligns with the three levels of SemVer). The Angular convention refines the commit types by providing others (such as `docs`, `style`, `refactor` and `test`) that may even not need to be released (for instance, there is not going to be a release just because we fixed indentation, or because we refactored a private method). I think it is be desirable to preserve that distinction in `build` vs `ci`.

**Comment by mlopezFC** [comment]
I think that we need more examples in order to understand the differences between build & ci. The pom.xml file contains a lot of things that, if modified, they could be interpreted as build or ci changes.

**Comment by javier-godoy** [comment]
@mlopezFC Looking at the history of a single addon (VerticalLayout) we have the following changes related to pom.xml:

- Update the version number
- Upgrade compile-scoped dependencies
- Upgrade test-scoped dependencies
- Add demo-jar profile
- Add production profile
- Replace `http` with `https` in repository URLs
- Upgrade version of maven-surefire-plugin
- Upgrade version of maven-release-plugin
- Upgrade version of maven-deploy-plugin
- Upgrade version of configuration of jetty-maven-plugin
- Change configuration of vaadin-maven-plugin
- Change configuration of license-maven-plugin: move license header above package
- Change configuration of jetty-maven-plugin
- Remove unused POM properties
- Correct the SCM configuration

What would be a good criteria for classifying them as either `build`  or `ci`?

**Comment by mlopezFC** [comment]
My proposal is the following. We can use:

*  `build` if the commit will alter in some way what is being built (the produced artifacts) in the regular build process
* `ci` if the commit will alter the Continuous Integration configuration that might be versioned along the code (like a [JenkinsFile](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/) or something like that). Another example would be that the commit will alter the configuration of the steps that are part of the ci process, but it won't update the generated artifacts (ie: deploying to a given repository or tagging the VCS in a certain way)

For the examples that you provided these are the types that I think should be used:

- Update the version number: This could be `build` (because in java it somehow alters the generated artifact) or `ci`
- Upgrade compile-scoped dependencies: `build` 
- Upgrade test-scoped dependencies: `build` (because the test artifacts are generated before running the test, so it will affect the generated artifacts)
- Add demo-jar profile: `build`
- Add production profile: `build`
- Replace http with https in repository URLs: `build` (because it will allow the generated artifact to be built, thus altering it)
- Upgrade version of maven-surefire-plugin: `test` if we're solving a test execution issue with the upgrade. Could also be `chore` if we're just upgrading to the latest version. But this will not affect the produced artifact.
- Upgrade version of maven-release-plugin: `ci` because it's affecting the steps that are executed after packaging the artifact
- Upgrade version of maven-deploy-plugin: `ci` because it's affecting the steps that are executed after packaging the artifact
- Upgrade version of configuration of jetty-maven-plugin: `ci` if that plugin is somehow used in the ci process, but if not then probably `chore`
- Change configuration of vaadin-maven-plugin: probably `build` because it could affect the generated artifact
- Change configuration of license-maven-plugin: move license header above package: probably `style` y if in the same commit we're including the changes in the java files, or `chore` if not.
- Change configuration of jetty-maven-plugin: `ci` if that plugin is somehow used in the ci process, but if not then probably `chore`
- Remove unused POM properties: probably `chore`
- Correct the SCM configuration: `ci`

**Comment by javier-godoy** [comment]
In general terms, I like the approach since it adds value to the commit message (instead of just committing `ci: modify pom`).

However, we will need to address #11 before this one, becaue `chore` is not well defined and some of the answers suggest using chore. 

Just one question: do you mean "artifacts" as "the released artifacts", or does it also consider any intermediate artifact exclusively created for CI purposes (i.e. artifacts such as test classes, which are needed for running the tests even if the tests are not released)?

**Comment by mlopezFC** [comment]
I agree with addressing that ticket before closing this one.
Regarding your question I consider that the build process will generate artifacts, and those might be used or not (ie: the javadocs in the libraries, the ci might or not run the test at a given point of time, etc.). 
So I think we should consider that every artifact that is generated by the build process can be potentially be used for something, thus a modification in the configuration that would affect them (if there is no other _dominant type_, I'm planning to discuss that in #12) should be tagged with _build_ type.

**Comment by javier-godoy** [comment]
> So I think we should consider that every artifact that is generated by the build process can be potentially be used for something, thus a modification in the configuration that would affect them should be tagged with build type.

I was thinking the opposite: an artifact generated by the build process for the only purpose of executing a CI task (such as compiling test classes in order to run unit tests) is just a consequence of CI and doesn't count as a `build`; otherwise `build` is too broad, and a separate type of `ci` doesn't add any value.
  
  - A `build` commit contributes changes that affect the final artifacts. 
  - A `ci` commit contributes changes that take effect during CI, but the final artifacts will be the same.
    
> Upgrade version of maven-surefire-plugin: test if we're solving a test execution issue with the upgrade. Could also be chore if we're just upgrading to the latest version. But this will not affect the produced artifact.

**ci** (because running tests is part of the CI process). Not a `chore` (according to what seems to be the current agreement in #12). Not `test` either, since it's defined as "adding missing tests or correcting existing tests".

> Upgrade test-scoped dependencies: build (because the test artifacts are generated before running the test, so it will affect the generated artifacts)

**ci** (because those dependencies are not part of the product, they are only used when running tests). If the dependencies are wrong and that causes a test to fail, that will not *affect* the artifact, it will just prevent it's existence (or it will affect the artifact by preventing its existence). After the artifact is generated, it will be the same artifact that we had before that change. (If test artifacts are part of the product, it might make sense to consider these as `build` changes.)

> Upgrade test-scoped dependencies: build (because the test artifacts are generated before running the test, so it will affect the generated artifacts)
**ci** (because those dependencies are not part of the product, they are only used when running tests)

> Add a profile: build
**build/ci/chore** (based on dominance, depending on how the profile affects the artifact).

**Comment by mlopezFC** [comment]
Yes, now I think this deeply, the developer (or team, or leader that is reviewing the PRs) are going to be aware if the test artifacts created from one of the maven modules are going to be used in a different module as a dependency or not. If the generated test artifacts from one module are consumed as dependencies from another module, then they are part of the "generated product" and changes that affect the build process in such a way that they are affected should be `build`.
In the large majority of real life cases, those changes are `ci`, because they are affecting the continuous integration process (considering that a test is a step towards building the final product, if the tests fail the final product should not be built or used).
Your proposal of ci and test are fine but maybe we need to add a definition of "final artifacts", or maybe replace that with "exported artifacts". Something like: "_Artifacts that are created as a result of the build process and are utilized as final deliverables or included in other external projects_" ... but I'm not sure, do you have a better idea?

**Comment by javier-godoy** [comment]
I think your proposed wording is clear. (Other alternatives for "exported" are "deployed" or "published", but they could be misunderstood. I think the idea is better conveyed by using "exported").

So will have:

  - `build:` Changes to the build process or external dependencies affecting the exported artifacts (i.e. those artifacts that are created as a result of such process, and are utilized as final deliverables or included in other external projects).
  - `ci:` Changes to the CI configuration, and other changes to the build process or external dependencies with no impact in the exported artifacts (e.g.: configure code quality metrics, add dependencies that are only needed for running unit tests).

Instead of:

  - `build:` Changes that affect the build system or external dependencies (e.g.: configure plugins and dependencies in pom.xml) 
 - `ci:` Changes to our CI configuration files and scripts, with no impact in the released artifact (e.g.: set metadata and profiles in pom.xml, edit DockerFile) 

Do you agree?

**Comment by mlopezFC** [comment]
Yes, let's go ahead with those definitions, I think that they supply more value than the current ones 👍

**Comment by javier-godoy** [comment]
Modified:
>  - `build:` Changes to the build process or external dependencies affecting the exported artifacts (i.e. those artifacts that are created as a result of such process, and are utilized as final deliverables or included in other external projects). Correlates with a PATCH, MINOR or MAJOR increment in semantic versioning, depending on the nature of the change
>  - `ci:` Changes to the CI configuration, and other changes to the build process or external dependencies with no impact in the exported artifacts (e.g.: configure code quality metrics, add dependencies that are only needed for running unit tests). Does not correlate with an increment in semantic versioning, because the versioned artifacts are not modified
