### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/DevelopmentConventions#3]
Should the body and the footer be capitalized?

**Comment by javier-godoy** [comment]
> Should *body* be capitalized?

**YES**. (IMHO) because "a commit body is free-form and MAY consist of any number of newline separated paragraphs."
Thus the first letter of the first sentence of the first paragraph should (must?) be capitalized.
And it should/must end with a period, too.

**NO**. See the [following example](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers):

```
fix: correct minor typos in code

see the issue for details on typos fixed.

Reviewed-by: Z
Refs #133
```

> Should *footer* be capitalized?

**YES**. `BREAKING CHANGE` (as an exception) is required to be uppercase.

**YES**. The other footers are formally case insensitive, but from the examples in https://git-scm.com/docs/git-interpret-trailers  and https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html#when-to-use-acked-by-cc-and-co-developed-by I understand that the recommendation is capitalizing the first letter of the footer.


What do you think?

**Comment by mlopezFC** [comment]
Yes, I agree with everything, so basically we would be "customizing" or changing [what is specified in ConventionalCommits](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers), so that example in our case should be something like this:

```
fix: correct minor typos in code

See the issue for details

On typos fixed.

Reviewed-by: Z
Refs #133
```
Am I right?

**Comment by javier-godoy** [comment]
> so basically we would be "customizing" or changing what is specified in ConventionalCommits,

We would be extending ConventionalCommits by adding a constraint on *body*.  ConventionalCommits doesn't impose any restriction, hence both your example and mine are conforming. 

The question regarding *body* is whether we want to:
- Restrict that *body* must begin with an uppercase letter (an absolute requirement) and that it must not begin with a lowercase letter (an absolute prohibition).
- Weakly recommend that *body* begins with a uppercase letter, while allowing committers to start it with lowercase letter if they feel so inclined.
- Allow *body* to begin with either an uppercase or lowercase letter.

**Comment by mlopezFC** [comment]
I'm between 1) and 2). If I understand correctly the body part will provide _additional contextual information about the code changes_. If 72 characters in the subject were not enough for explaining the commit, and that additional info is needed, then it's reasonable to assume that paragraphs are going to be included in the body for that explanation. For easier reading of those paragraphs, they should be well formed (starting with a capital letter and ending with a dot). 
What do you think?

**Comment by javier-godoy** [comment]
I agree. The pending question is whether we are going to request a rewriting of the commit because *body* starts with lowercase or doesn't end with a period.

**Comment by mlopezFC** [comment]
That might be too strict, I would go with uppercase and ending period strong recommendation for body, but without demanding a rewriting of the commit if those recommendations are not used.

**Comment by javier-godoy** [comment]
Makes sense. The weak/strong difference is kind of lost anyway, since I'm (intentionally) not using [RFC 2119](https://tools.ietf.org/html/rfc2119) keywords.

**Comment by javier-godoy** [comment]
Added: 
> The commit body is free-form text and may consist of any number of newline separated paragraphs. It may contain URIs and links to other issues.
>
> If possible, use the imperative present tense ("change" not "changed" nor "changes") and follow basic grammar rules: capitalize the first letter, end each sentence with a period, etc. This restriction can be relaxed.
