### ISSUE TITLE
What type to use for visual content changes?

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#5]
The `style` type addresses *changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)*. We need to clarify (through an example) that changes to the application "styles" (Cascading _Style_ Sheets_) and visual content are not `style` commits.

https://github.com/conventional-commits/conventionalcommits.org/issues/240 seems to suggest `refactor` or `chore` (when the visual change is by itself neither a `feat` nor a `fix`). However, we are defining `refactor` as "a **code** change" (thus replacing a PNG would not be covered under this type). 

chore: Maintenance changes not covered by other types.
refactor: A code change that neither fixes a bug nor adds a feature
feat: A new feature (correlates with MINOR in semantic versioning)
fix: A bug fix (correlates with PATCH in semantic versioning)

**Comment by mlopezFC** [comment]
Totally, we need to clarify that.
IMHO I think it's clear which of those options to choose, here are some examples (based on style changes):

- chore: replace px with em widths
- refactor: use css variables instead of hardcoded values
- feat: improve readability by using larger fonts
- fix: fix overlapping problem in divs

**Comment by javier-godoy** [comment]
Will provide clarification through examples. Feel free to reopen if you consider that we need to rewrite other parts of the document.
