### ISSUE TITLE
Related comments or commits

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/DevelopmentConventions#6]
I think we can discuss where could be a good place to quote or mention comments or issues that are related to the commit, maybe in the footer before the last "Closes #xx" line, or with a subtitle like the BREAKING CHANGES description.

**Comment by javier-godoy** [comment]
One option could be mentioning the issue / URL in the commit _body_

``` 
fix(students): sanitize database input

As discussed in #nn the Students form is open to SQL injection.
See also https://xkcd.com/327/
```

Since that is "additional information" we could also use a footer (which allows for defining some link-verbs such depending on why it is linked)

``` 
fix(students): sanitize database input

Part-of #nn
See: https://xkcd.com/327/
```

What do you think?

**Comment by mlopezFC** [comment]
I don't see a reason why we can't mention the issue in the subject. If we're talking about mentioning the issue, I think it could be mentioned anywhere.
BUT for executing actions like Closes #xxx (that will close an issue) then the footer is the place that the specification mentions as the place to use them. Anyway I do not see why something like this cannot be used: `feat(test): fixes #xx`

**Comment by javier-godoy** [comment]
>  I think it could be mentioned anywhere.
+1

>  I do not see why something like this cannot be used: `feat(test): fixes #xx`

Because it doesn't **describe** the change, it's just a pointer to the issue tracker where the fixed behavior is actually described. Moreover, conventional commits allow generating release notes from the commit history. With that approach the release notes would read "Bugfixes: #xx, #yy and #zz".

One could write something like `fix(security): fix #xx by validating user password`, but the *header* is already constrained to a maximum of 72 characters, thus it some fixes won't be able to be mentioned that way, leading to inconsistent formatting.

A minimal commit message for that case would be:

Leaving aside the discussion on which verb we are using for closing issues (i.e. whether bugs are fixed and features are resolved, or evertything is just "closed"). One could specify the closed issue as:
```
fix(security): validate user password

Fixes #xx
```
(However, this issue wasn't about GitHub verbs, feel free to create an issue if you consider that has to be discussed.)

**Proposed action**: clarify that issues can be linked from the *body*.

Do you agree?

**Comment by mlopezFC** [comment]
Great analysis.
Now I understand why something like `feat(test): fixes #xx` is not correct.
And now I also realize that this issue is not about GitHub verbs, but just a question about where to _link_ an issue (link = mention).
I agree with the proposed action.

**Comment by javier-godoy** [comment]
Added: 
> The commit body is free-form text and may consist of any number of newline separated paragraphs. It may contain URIs and links to other issues.
